import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "La CLEF",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
